services:
 app:
   build: 
     context: .
     dockerfile: ./Dockerfile
   image: lildrughill/devops-for-programmers-project-74:v1
   volumes:
     - ".env.example:/app/.env"
   ports:
     - "8080:8080"
   depends_on:
     - db

 db:
  image: postgres
  restart: always
