services:
 app:
   build: 
     context: .
     dockerfile: ./Dockerfile
   image: lildrughill/devops-for-programmers-project-74:v1
   ports:
     - "8080:8080"
   volumes:
     - ".env.example:app/.env"
   depends_on:
     - db

 db:
  image: postgres
  env_file:
    - .env
  restart: always
