services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    command: bash -c 'sleep 3 && npm start'
    ports: 
      - "8080:8080"
    volumes:
      - "./app:/app"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_DB: ${DATABASE_NAME}
