services:
 app:
   build:
     context: .
     dockerfile: ./Dockerfile.production
   image: lildrughill/devops-for-programmers-project-74:v1
   command: npm test
   environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}

   volumes:
     - ".env.example:/app/.env"
   depends_on:
     - db

 db:
  image: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    POSTGRES_USER: ${DATABASE_USERNAME}
    POSTGRES_DB: ${DATABASE_NAME}
